Configuring linters and readme file
FilbertKimasa/Hello-Microverse pull request #1
Opened 2023-06-01 14:39 UTC by FilbertKimasa

**In this branch, the following was done:**
1. Add a .html file
2. Add a .css file
3. Configuring linters
4. Editing a readme file

2023-06-01 20:23 UTC, shahadat3669 requested changes
Hi @FilbertKimasa , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media4.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif"/>

## Highlights
✅ Descriptive PR title and summary.
✅ Descriptive commit messages.
✅ No linters errors.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me using @shahadat3669 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-01 20:23 UTC, shahadat3669 commented on README.md
> +- Twitter: [@twitterhandle](https://twitter.com)
- [ ] Well done on adding the Author section to your project's Readme file! It's great to see that the Github and LinkedIn links are working perfectly, allowing users to easily access your profiles. However, I noticed that the Twitter link provided is broken. To ensure a seamless user experience and allow users to connect with you through Twitter, please update the broken Twitter link. :pray:

2023-06-01 20:23 UTC, shahadat3669 commented on README.md
> +- [❓ FAQ (OPTIONAL)](#faq)
- [ ] Great job on including a FAQ section in your Readme file :grinning: and adding it to the Table of Contents! It's excellent to see that you're providing additional information and addressing potential user questions. However, there is a minor adjustment that needs to be made regarding the indication of the FAQ section as optional in the Table of Contents.

Please remove the "optional" label from the FAQ. This will maintain clarity and consistency in the Table of Contents presentation.

| Your | Professional |
| --- | --- |
|   ![image](https://github.com/FilbertKimasa/Hello-Microverse/assets/55840999/1ba4c68e-a0fe-44fc-9d0a-438328fae01b) | ![image](https://github.com/FilbertKimasa/Hello-Microverse/assets/55840999/e2f7e31f-1334-47fe-b646-381649f1d4e9) |

2023-06-01 20:23 UTC, shahadat3669 commented on README.md
> -<p align="right">(<a href="#readme-top">back to top</a>)</p>
Good Readme file👍 However, it would be good to add "future features" and include 1-3 potential features in this section. Remember in this section, you should outline your plans for the future development of the project. Include details about the features, functionalities, or improvements you intend to add. It should demonstrate your vision and give readers an idea of what to expect. Keep up the good work!

Please include 1-3 potential fractures in this section. Please also remember to add Feature Feature in "Table Of Content"

| Your | Professional |
| --- | --- |
| ![image](https://github.com/FilbertKimasa/Hello-Microverse/assets/55840999/59b49720-c936-40b1-9de3-5a7166ca1bad)  | ![image](https://github.com/2004-okari/HELLO_MICROVERSE/assets/55840999/6c06d9c5-1153-4928-bfd9-d55057f77c97) |

2023-06-01 20:23 UTC, shahadat3669 commented on README.md
> +- [🤝 Contributing](#contributing)
- [ ]  Good, you have **contributing** in the table of contents. But upon reviewing your Readme file, I noticed that there is no contribution section included. It is important to provide a clear and informative contribution section in your Readme file, as it allows visitors to understand how they can contribute to your project.
Please add a contribution section. :pray:

| Your | Professional |
| --- | --- |
| ![image](https://github.com/FilbertKimasa/Hello-Microverse/assets/55840999/b586f92c-5634-468a-8569-57e379550b15) | ![image](https://github.com/FilbertKimasa/Hello-Microverse/assets/55840999/39503755-5f1d-489b-a783-1122f9129843)  |

2023-06-01 20:23 UTC, shahadat3669 commented on .gitignore
> +test.md
Great work! As required you added a `test.md` file in the `,gitignore` file. But little changes are required. As per requirement, You should add  `A test.md file with the text "This file should be ignored by git".` add commit it. :x:
Upon reviewing your commit history I did not fount any commit related to it. Please follow the requirement carefully and update accordingly.
![image](https://github.com/FilbertKimasa/Hello-Microverse/assets/55840999/6f5a4640-9caf-4d02-82fa-e0d566dcf0f2)

2023-06-03 04:56 UTC, Cabraham1 requested changes
# Required Changes :recycle:
![almost-there](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Hey @FilbertKimasa   :wave:

## Highlights :1st_place_medal:

✔️ Descriptive PR Title
✔️ Descriptive PR Summary
✔️ Following some requirements

- [ ] Good job on implementing some of the requirements, there are some issues that you still need to work on to go to the next project but you are almost there! :blush:
- [ ] I noticed that some important header sections are missing in your readme file. To provide more comprehensive and well-structured documentation for your project, I recommend adding a section for future features.

- Please consider including a "Future Features" section where you can outline any planned or anticipated features that you intend to add to the project in the future. This will give users and potential contributors insights into the roadmap of your project and generate excitement for upcoming enhancements. 


### _**Your README**_ 🔽
![image](https://github.com/FilbertKimasa/Hello-Microverse/assets/68823331/2ec6059f-8647-4c9f-b467-d945acee9f02)


### _**README template**_ 🔽
![image](https://user-images.githubusercontent.com/106119105/212086927-b85c4157-b8dc-48ac-894a-5ccbd88ea6fb.png)

You can take a step back and read the [lesson](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) for more clarity 💡


# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers, and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-03 05:27 UTC, FilbertKimasa commented
Hello @Cabraham1 the review requires me to add a future feature section, but it is already there . Could you please make it clear to me?

2023-06-03 05:35 UTC, Cabraham1 commented
@FilbertKimasa Nice to hear from you. If you look closely you can see from microverse template the location of the future features but yours is not so please 🙏 I recommend you follow the structure of the readme to align with your okay 👍😁🎉

2023-06-03 18:37 UTC, Bantealem approved these changes
Hi @FilbertKimasa , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- [x] Professional Readme
## Optional suggestions
- [ ] Your Pr has a GitHub conflict that's why I can't see Linters check on the browser.  It is not professional and it will complicate your file. Kindly resolve it. You can find the [tutorial here](https://youtu.be/xNVM5UxlFSA)
![image](https://github.com/FilbertKimasa/Hello-Microverse/assets/101523582/f2147d56-1eee-4bf6-9245-36e10d747459)


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-07 18:13 UTC, closed without merging